spring.application.name=MQService


destination.reservationNotification=reservation_notification_queue
destination.modificationNotification=modification_notification_queue
destination.cancellationNotification=cancellation_notification_queue